### ISSUE TITLE
 Cannot open beamerthemesuse-logo.eps: No such file or directory

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/beamertheme-suse#1]
Hi there,

first of all: Great job.

When I copy the `*.sty` and`*.eps` file into my working directory, my beamer document compiles. However, if I copy the theme into my texmf directory, `lualatex` fails to find the `eps` file:

```
!!! Error: Cannot open beamerthemesuse-logo.eps: No such file or directory


! Package luatex.def Error: File `beamerthemesuse-logo-eps-converted-to.pdf' no
t found: using draft setting.
```

This seems to be an issue specific to `lualatex`:

* using `xelatex` the document compiles
* using a `.png` instead of the `.eps` would also work

**Comment by dmacvicar** [comment]
I have only tested Xelatex

If I remember correctly I converted from SVG to EPS because I understood it would result in a vector logo.

**Comment by crazyscientist** [comment]
Unfortunately I don't know too much about all the different (La)TeX flavors.

**Comment by dmacvicar** [comment]
I chose XeTeX because of utf8 and TrueType font support.

I understand there is no major reason to use Luatex other than scripting:
https://tex.stackexchange.com/questions/36/differences-between-luatex-context-and-xetex

Would you mind sticking to xelatex?

**Comment by crazyscientist** [comment]
I get your arguments. I only chose LuaTex, because it is required by the [plantuml package](https://www.ctan.org/tex-archive/macros/luatex/latex/plantuml), but that one does not work nicely wit the beamer document class. So XeTex is working just fine for me.

Once that issue is resolved I might want to try LuaTex again.
