### ISSUE TITLE
verbments does not see build directory

### ISSUE THREAD

**Issue by pevik** [SUSE/beamertheme-suse#13]
@beninidavide You added in 8bdd5313803dd47e33dc3909a12e2e306a8b3ff6 output in `BUILDDIR`, but that directory is not visible by `verbments` package:

```latex
\usepackage{verbments}
...
\begin{frame}[fragile]
\frametitle{Foo}
\begin{pyglist}[language=java]
// Hello Java program
\end{pyglist}
\end{frame}
```

fails: `! LaTeX Error: File iputils-project-introduction.pyg.vrb' not found.` because `iputils-project-introduction.pyg.vrb` is in the root directory, not in build directory but in root directory.

Test on this:
```diff
diff --git Makefile Makefile
index 26b3e79..cef7f98 100644
--- Makefile
+++ Makefile
@@ -12,7 +12,7 @@ all: documents screenshots
 documents: $(DOCUMENTS)
 
 $(BUILDDIR)/%.pdf: %.tex | $(BUILDDIR)
-       xelatex -interaction=nonstopmode -output-directory=$(BUILDDIR) $<
+       xelatex -interaction=nonstopmode -shell-escape -output-directory=$(BUILDDIR) $<
 
 screenshots:   $(SCREENSHOTS)
 
diff --git example.tex example.tex
index d3e02f9..10e2674 100644
--- example.tex
+++ example.tex
@@ -2,6 +2,7 @@
 \usepackage[T1]{fontenc}
 \usepackage[utf8]{inputenc}
 \usepackage{listings}
+\usepackage{verbments}
 
 \title{Presentation Title}
 \date{July 25, Nuremberg}
@@ -14,6 +15,13 @@
 \titlepage
 \end{frame}
 
+\begin{frame}[fragile]
+\frametitle{\File{ping}}
+\begin{pyglist}[language=java]
+// Hello Java program
+\end{pyglist}
+\end{frame}
+
 \begin{frame}[fragile]
 \frametitle{Presentation Title}
 \framesubtitle{This is \textit{a subtitle}.
```

**Comment by pevik** [comment]
OK, it's possible to use `lstlisting`, thus closing this.

**Comment by Werkov** [comment]
Uh, first time I hear about `verbments`, last update in 2011. `lstlisting` seems like a better choice anyway.

**Comment by pevik** [comment]
Agree. I used in the past `minted`, but even with `-shell-escape` it did not work. And `verbments` was said to be `minted` replacement, but obviously it's not true ( `minted` is actively maintained). But `minted` also did not work for me even with `-shell-escape`.
